telegram:
  api_id: '37009125'
  api_hash: ' 3d2bd76f2d6380f91ab4599ce4a202ff'
  lib: telethon
  account:
    session_file: account.session
    used_to_upload: false
    used_to_download: false
  bot:
    session_file: bot.session
    tokens:
      - 8695600581:AAHIEQM8RqJkt455dew7FG7Od3kdCVM_qtE
  private_file_channel:
    - '-1003737989778'
tgfs:
  users:
    username:
      password: password
  download:
    chunk_size_kb: 1024
  jwt:
    secret: f+r$J[{jVt,WFFxY:bnau?W@|>{oVI@gL^8l<dB1QYIa,^)JwN[jkjtk7%Z%w_8Y
    algorithm: HS256
    life: 604800
  metadata:
    '-1003737989778':
      name: Database
      type: pinned_message
      github_repo:
          repo: m3almakinsts/tgfs
          commit: master
          access_token: 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
  server:
    host: 0.0.0.0
    port: 1900
